name: Build My APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Love File
        run: zip -9 -r juice.love .

      - name: Download Engine
        run: |
          curl -L -o love-android.apk https://github.com/love2d/love-android/releases/download/11.4/love-11.4-android-universal.apk

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Final-Game-Package
          path: |
            juice.love
            love-android.apk
