name: Build Game APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .love File
        run: zip -9 -r juice.love .

      - name: Build Android APK
        uses: akatake/love-android-builder@main
        with:
          version: 11.4
          bundleId: com.raven.juice
          appName: JuiceGame
          loveFile: juice.love
